"use client";
import Link from "next/link";
import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { signIn, signUp } from "../../lib/localAuth";

export default function LoginPage() {
  const [mode, setMode] = useState<"login" | "signup">("login");
  const [email, setEmail] = useState(""); const [name, setName] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState(""); const router = useRouter();
  function submit(event: FormEvent) { event.preventDefault(); setMessage(""); try { if (password.length < 8) throw new Error("Password must have at least 8 characters."); if (mode === "login") signIn(email, password); else signUp(name, email, password); router.push("/"); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to continue."); } }
  return <main className="auth-page"><section className="auth-story"><Link className="auth-brand" href="/"><span>A</span>AssetFlow</Link><div><p className="eyebrow">Enterprise operations</p><h1>Every asset.<br />One source of truth.</h1><p>Track ownership, eliminate booking conflicts, and keep every asset ready for work.</p></div><small>Secure role-based access · Complete activity trail</small></section><section className="auth-form-wrap"><div className="auth-form"><p className="eyebrow accent">Welcome to AssetFlow</p><h2>{mode === "login" ? "Sign in to your workspace" : "Create your employee account"}</h2><p>{mode === "login" ? "Use your organization email to continue." : "An administrator can assign elevated roles after signup."}</p><form onSubmit={submit}><label>Work email<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required placeholder="you@organization.com" /></label>{mode === "signup" && <label>Full name<input value={name} onChange={(event) => setName(event.target.value)} required placeholder="Your full name" /></label>}<label>Password<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} required placeholder="At least 8 characters" /></label>{mode === "login" && <div className="form-row"><label className="checkbox"><input type="checkbox" /> Keep me signed in</label><button type="button" className="text-button">Forgot password?</button></div>}<button className="auth-submit" type="submit">{mode === "login" ? "Sign in" : "Create employee account"}</button>{message && <p className="auth-error" role="alert">{message}</p>}</form><div className="role-note"><strong>Role assignment is protected</strong><span>New accounts are always created as Employees. Only an Administrator can promote Department Heads or Asset Managers.</span></div><p className="auth-switch">{mode === "login" ? "New to AssetFlow?" : "Already have an account?"} <button type="button" onClick={() => { setMode(mode === "login" ? "signup" : "login"); setMessage(""); }}>{mode === "login" ? "Create account" : "Sign in"}</button></p></div></section></main>;
}
